---
galaxy_info:
  author: Patrick M. Slattery
  description: Remove deployed httpd Docker container(s)
  company: MyWebGrocer
  license: BSD
  min_ansible_version: 2.2.0
  platforms:
  - name: EL
    versions:
    - 7
  categories:
  - cloud
  - system
dependencies: []
